# Sudoku Solver

In [7]:
import numpy as np

In [130]:
game = np.matrix([
        [0,0,0,0,0,0,0,0,0],
        [0,0,9,0,0,0,0,6,0],
        [0,0,5,0,0,2,0,0,0],
        [0,0,4,3,9,0,5,2,6],
        [0,5,0,0,6,0,0,7,3],
        [0,0,8,0,0,0,1,0,9],
        [3,8,0,0,0,0,0,0,4],
        [0,0,6,0,0,7,0,0,1],
        [5,0,0,0,0,6,0,0,0]])


## check wheather a play is valid

In [66]:
def isAllowed(x,y,p):
    for elem in game.getA()[x]:
        if elem == p:
            return False
    for i in range(9):
        if game.getA()[i][y] == p:
            return False
    
    # Identifikation starting block for 3x3 analysis
    bx = ((int) (x/3))*3 
    by = ((int) (y/3))*3
    
    for xi in range(bx,bx+3):
        for yi in range(by, by+3):
            if p == game.getA()[xi][yi]:
                return False
    return True
    

In [126]:
def solver():
    #print("entered")
    global game
    for x in range(9):
        for y in range(9):
            #print(x, end="")
            #print(y)
            #print(game.getA()[x][y])
            if(game.getA()[x][y]) == 0:
                for p in range(1,10):
                    #print("p= {}".format(p))
                    if isAllowed(x,y,p):
                        #print("allowed")
                        game.getA()[x][y] = p
                        solver()
                        game.getA()[x][y] = 0
                return
    print(game.getA())
    print()

In [131]:
solver()

[[1 2 3 6 8 4 7 9 5]
 [8 7 9 1 5 3 4 6 2]
 [4 6 5 9 7 2 3 1 8]
 [7 1 4 3 9 8 5 2 6]
 [9 5 2 4 6 1 8 7 3]
 [6 3 8 7 2 5 1 4 9]
 [3 8 7 2 1 9 6 5 4]
 [2 4 6 5 3 7 9 8 1]
 [5 9 1 8 4 6 2 3 7]]

[[1 7 3 6 5 4 2 9 8]
 [8 2 9 1 7 3 4 6 5]
 [4 6 5 9 8 2 3 1 7]
 [7 1 4 3 9 8 5 2 6]
 [9 5 2 4 6 1 8 7 3]
 [6 3 8 7 2 5 1 4 9]
 [3 8 7 2 1 9 6 5 4]
 [2 4 6 5 3 7 9 8 1]
 [5 9 1 8 4 6 7 3 2]]

[[1 7 3 6 5 4 2 9 8]
 [8 2 9 7 1 3 4 6 5]
 [4 6 5 9 8 2 3 1 7]
 [7 1 4 3 9 8 5 2 6]
 [9 5 2 4 6 1 8 7 3]
 [6 3 8 2 7 5 1 4 9]
 [3 8 7 1 2 9 6 5 4]
 [2 4 6 5 3 7 9 8 1]
 [5 9 1 8 4 6 7 3 2]]

[[1 7 3 6 8 4 2 9 5]
 [8 2 9 1 5 3 4 6 7]
 [4 6 5 9 7 2 3 1 8]
 [7 1 4 3 9 8 5 2 6]
 [9 5 2 4 6 1 8 7 3]
 [6 3 8 7 2 5 1 4 9]
 [3 8 7 2 1 9 6 5 4]
 [2 4 6 5 3 7 9 8 1]
 [5 9 1 8 4 6 7 3 2]]

[[2 4 3 6 7 1 9 8 5]
 [1 7 9 5 8 3 4 6 2]
 [8 6 5 9 4 2 3 1 7]
 [7 1 4 3 9 8 5 2 6]
 [9 5 2 1 6 4 8 7 3]
 [6 3 8 7 2 5 1 4 9]
 [3 8 7 2 1 9 6 5 4]
 [4 9 6 8 5 7 2 3 1]
 [5 2 1 4 3 6 7 9 8]]

[[2 4 3 6 7 1 9 8 5]
 [1 7 9 8 5 3 4 6 2]
 [8